sudo: required
services:
- docker
before_install:
- curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose build
script:
- docker-compose up -d
deploy:
  provider: heroku
  api_key:
    secure: MplX4AkhpuYj1mkjMlwb0a034Dx3xSm0gFeuzxh85mCeNBBYmGvPOh0I8WZ1NVSKDmAgCA0O7W3iVdL71xMNEZkV58a9hSPMktqM7WwStjq5iBCh3dftZTR4beqPSYCegDW3oK37exrroi2Cyfc6sGWpFtTyAbpsZRoqG7X37nQo/4sbJ942rOP9hARHDguejQW9JDNaFK3SltVF8XrJ6jBFMjtWIvO/TZBeJv78pHBOZ4bDQyDjIsWHj2kxETmQWUDXhKeBNkPXYqTuv0vQ0eTH5a8LvAYKj726xpFKwVglvIHsmEHt3Vmb3Iw0GqkRdSSZBodAa/c77q8RPY1VjhaYYIS5AVN6SLBvrq2/8dplKd/bEf7BtnKbFFvlm2MRreq5ZsA33Eu6JptWtZLnA0NtZ2uPu+oOWtWPLwIX4Z/p3N9S075w+loTP33KaFVZ3TG6g5VglfDzoC51gIyy/ZYPTCvc5Y0CmqC2nWqZzuUfLJmH3tEdHinyBI5K311G915h+0NgsFds40044Fi5m83QTLHUtlScsMbFn7MZkhQXVtbNadgHs3dNxYGoS/BllC3Va8p2ArL3GtR1yvt/KTEtlf8fmwdbxGWwK4hJI0ekuc4yAWAPlH5XddbGbAoBfOt2Q95/5hOB/VcVJCZucf0zgmPrdsvcplU+zZMmvwA=
  app: dcsunity-rserver
  on:
    repo: defint/rserverpro
